name: Build and Deploy Quarto Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.550'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.12"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Build Quartodoc API docs
        run: |
          source .venv/bin/activate
          quartodoc build --config docs/_quarto.yml

      - name: Render Quarto site
        run: |
          source .venv/bin/activate
          quarto render docs/

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
